### ISSUE TITLE
Application in fullscreen does not change its size

### ISSUE THREAD

**Issue by Camiropan** [Leleat/Tiling-Assistant#177]
**Describe the bug**
if an application is in fullscreen (or even wider) and you want to tile it, the size does not change.

**Steps To Reproduce**
1) Have a application in fullscreen or wider (e.g. Nautilus).
2) Open an other application.
3) Drag the non-fullscreen application to the left edge (or which does not have the second monitor next to it).
4) Choose the fullscreen-app via the App-picker.

You should see that the fullscreen app has his old size and the app picker pops up on the second screen. 
So the fullscreen app stretches across both screens.

**System Info:**
 - Distro (incl. version): Fedora 36
 - GNOME (Shell) version: 42.1
 - Extension version and from where (e. g. EGO, `main` branch...): main
 - XOrg/Wayland: Wayland

**Journalctl logs**

Error in size change accounting.

**Comment by Leleat** [comment]
I am able to reproduce this. It appears to only happen under Wayland. Removing the line https://github.com/Leleat/Tiling-Assistant/blob/main/tiling-assistant%40leleat-on-github/src/extension/tilingWindowManager.js#L206= seems to fix it. That line was originally meant as a workaround but I can no longer reproduce the original issue which the workaround was meant to... work around.

Can you remove that line from your local extension, test it for a few days/weeks and see if you notice any new tiling issues (like windows not tiling like they should). Please report any regressions.

**Comment by Camiropan** [comment]
Yes, i will report in a week or so :+1:

**Comment by Camiropan** [comment]
I have found three bugs. Unfortunately I don't know if it's related to the line I removed...

On the main Monitor, tiling with fullsize applications works fine... But on the second (the right one for me) it doesn't.
For example: open an app on your second screen, make it fullsize, drag another app to a corner on your main screen and then choose via the app-picker the fullscreen-app. Things start to get weird.

Tile (on your main screen) two applications in 1:1 vertical. Now drag the app with contact to your second monitor (for me its the right one) out of the tiling and drag it to the top corner on your second screen so that it would fit in a 2:2 grid. Sometimes things starts getting weird.
(if it doesn't work the first times try to resize the 1:1 grid a bit)

Oddly enough, LibAdwaita-apps can't be bigger than the main screen.
(try to resize a LibAdwaita-app bigger than your screen. When you release your mouse button, it jumps to the size of your main screen)

GNOME (Shell) version: 42.2

**Comment by Leleat** [comment]
> On the main Monitor, tiling with fullsize applications works fine... But on the second (the right one for me) it doesn't.
For example: open an app on your second screen, make it fullsize, drag another app to a corner on your main screen and then choose via the app-picker the fullscreen-app. Things start to get weird.

That isn't caused by the change I suggested above. It's a pre-existing issue and also a GNOME bug(?). You can reproduce this by trying to move the big window from the right to the left monitor with `looking glass` (`Alt`+`F2` > Enter `r`) by entering `global.display.focus_window.move_resize_frame(true, 50, 50, 500, 500);`. The window will stay on the right monitor. I don't think there is any way for me to work around that. Curiously though, this doesn't apply to all windows. VSCode for example didn't have this issue.

I'll try opening an issue on mutter and see if they consider it a bug.

> Tile (on your main screen) two applications in 1:1 vertical. Now drag the app with contact to your second monitor (for me its the right one) out of the tiling and drag it to the top corner on your second screen so that it would fit in a 2:2 grid. Sometimes things starts getting weird.
(if it doesn't work the first times try to resize the 1:1 grid a bit)

Sorry, didn't understand this issue / couldn't reproduce it.

**Comment by Camiropan** [comment]
Sorry for the late response.
I can't reproduce it myself, so it seems that its been fixed by the version 35 or the latest Gnome-update.

**Comment by Leleat** [comment]
You mean the second part; the original issue still exists, right?

> > On the main Monitor, tiling with fullsize applications works fine... But on the second (the right one for me) it doesn't.
> > For example: open an app on your second screen, make it fullsize, drag another app to a corner on your main screen and then choose via the app-picker the fullscreen-app. Things start to get weird.
> 
> That isn't caused by the change I suggested above. It's a pre-existing issue and also a GNOME bug(?). You can reproduce this by trying to move the big window from the right to the left monitor with `looking glass` (`Alt`+`F2` > Enter `r`) by entering `global.display.focus_window.move_resize_frame(true, 50, 50, 500, 500);`. The window will stay on the right monitor. I don't think there is any way for me to work around that. Curiously though, this doesn't apply to all windows. VSCode for example didn't have this issue.
> 
> I'll try opening an issue on mutter and see if they consider it a bug.
> 
> > Tile (on your main screen) two applications in 1:1 vertical. Now drag the app with contact to your second monitor (for me its the right one) out of the tiling and drag it to the top corner on your second screen so that it would fit in a 2:2 grid. Sometimes things starts getting weird.
> > (if it doesn't work the first times try to resize the 1:1 grid a bit)
> 
> Sorry, didn't understand this issue / couldn't reproduce it.

**Comment by Camiropan** [comment]
exactly
