### ISSUE TITLE
Lag when dragging window.

### ISSUE THREAD

**Issue by gnat** [Leleat/Tiling-Assistant#181]
Lag when dragging window.

**Steps To Reproduce**

**System Info:**
 - Distro (incl. version): Ubuntu 22.04
 - GNOME (Shell) version: 42
 - Extension version and from where (e. g. EGO, `main` branch...): Latest available on https://extensions.gnome.org/extension/3733/tiling-assistant/ and fresh built from master (7bbc969) have the same issue.
 - XOrg/Wayland: x11

This person also is encountering the lag:

![image](https://user-images.githubusercontent.com/24665/176501731-eff24935-2995-4234-ba45-5853e88b7c69.png)

**Comment by Leleat** [comment]
> Lag when dragging window.

Do you mean there is a small lag at the start of the grab? If yes, then that's 'expected' behavior. The way how untiling a window with a grab works is:

- end the user initiated grab programmatically
- resize the window to its old size
- restart the grab programmatically

I guess that's where the lag comes from. There is an advanced setting to restore a window's original size after the user released the grab. That should get rid of the lag. Downside is pretty big though since you won't know where the window will end up.

If you have tried other tiling extensions without that lag, feel free to name them and I'll take a look at their code and see, if I can find a better method than the one I currently use...

**Comment by gnat** [comment]
Thank you for the quick response. 🙂

> Do you mean there is a small lag at the start of the grab?

Sadly no, it persists as long as one is dragging the window- Not just at the beginning.

WinTile does not suffer from any lag issues: https://github.com/Fmstrat/wintile

**Comment by Leleat** [comment]
> Sadly no, it persists as long as one is dragging the window- Not just at the beginning. It's very disruptive and noticable.

Hmm, the person on EGO only talks about a lagspike when untiling a window which I expected. So this seems like something different...

> GNOME (Shell) version: 42

> WinTile does not suffer from any lag issues: https://github.com/Fmstrat/wintile

That extension doesn't seem supported on GNOME 42?

Is there anything in `journalctl -fo cat /usr/bin/gnome-shell` when dragging a window around? What other extensions do you have enabled and could you provide a short screencast of the issue?

**Comment by gnat** [comment]
Exact same vanilla Ubuntu 22.04, same nvidia 510 proprietary driver, all extensions but Tiling Assistant disabled.

No noticeable lag on the following specs: 
* Ryzen 7 4800H (8 core)
* Geforce RTX 2060 mobile (6 gig)
* 64 gigs RAM

The lag is severe on:
* AMD Phenom ii 955 (4 core).
* Geforce 960 Ti (4 gig)
* 16 gigs RAM

I was ready to write it off as an issue with the older hardware or a bad driver, BUT WinTile has no lag on either system and is silky smooth, which makes this a concerning issue- This leads me to believe there's a performance issue somewhere in TA.

> That extension doesn't seem supported on GNOME 42?

Just added `shell-version` 42 to WinTile's `metadata.json`, and it worked fine, nothing special.

**Comment by Leleat** [comment]
Hmm, I am only running a Ryzen 3200u and don't notice any issues. Altough I don't know how it compares to a AMD Phenom ii 955 since that one seems fairly old. I guess I can try to remove unneccessary operations and see if it helps.

**Comment by Leleat** [comment]
So I pushed some changes to `main`. **Can you see if it improves it for your slower system?**

TBH though I don't think it will help much. The big difference in performance might come from the fact that Tiling Assistant and WinTile do their calculations/checks at different frequencies. T-A will start getting active whenever a window's position changes because T-A is listening to a signal of the window. WinTile on the other hand starts a timer when a window is grabbed and periodically performs its calculations until the grab is ended (by default every 500 ms). As a result T-A will perform its calculations a lot more often but in turn is also more precise. You may notice with WinTile, if you try to drag a window to the edge of your monitor that there is a slight delay until the tiling preview pops up (depending on the timer's exact timeout). With T-A there is no delay... well, if your system can run it smoothly.

Not sure how I feel about this yet. I might implement some kind of 'low performance mode' as an advanced setting where I do the timer-based approach as well.

**Comment by DrunkenToast** [comment]
I have the same issue and it makes the extension for me kinda unusable unfortunately.
I pulled and build the latest changes and the issue persists. 

The issue is consistently there when enabling and disabling the extension. Tested without any other extension enabled as well.

**System info:**
- Fedora 36
- AMD ryzen 7 4800H
- iGPU amdgpu drivers
- Nvidia RTX 2060M, nvidia drivers (however desktop is running in hybrid, so besides extra monitors, not loaded with nvidia drivers)
- 16GB RAM
I think my laptop is performant enough to run the extension without any issues.

**Comment by Leleat** [comment]
@DrunkenToast Does WinTile work for you smoothly like it does for OP?

> the WinTile extension has no lag on either system and is silky smooth, which makes this a concerning issue- This leads me to believe there's a performance issue somewhere in TA.
>
>>  That extension doesn't seem supported on GNOME 42?
>
> Just added shell-version 42 to WinTile's metadata.json, and it worked fine, nothing special.

**Comment by gnat** [comment]
Haven't forgotten about this, just waiting on another project before I can nuke the Phenom workstation to retry T-A on it.
> T-A will start getting active whenever a window's position changes because T-A is listening to a signal of the window. WinTile on the other hand starts a timer when a window is grabbed and periodically performs its calculations until the grab is ended (by default every 500 ms). 

I feel like you're correct in this observation: the update rate is likely the cause of the lag on the slower systems.

**Comment by DrunkenToast** [comment]
> @DrunkenToast Does WinTile work for you smoothly like it does for OP?
> 
> > the WinTile extension has no lag on either system and is silky smooth, which makes this a concerning issue- This leads me to believe there's a performance issue somewhere in TA.
> > > That extension doesn't seem supported on GNOME 42?
> > 
> > 
> > Just added shell-version 42 to WinTile's metadata.json, and it worked fine, nothing special.

It does work as intended, although as you have mentioned, the delay of snapping is somewhat annoying.
I do believe the timer is a solution to the problem but what bothers me is that not everyone has this issue, also people with worse performing hardware, curious if there is some other solution possible.

**Comment by DrunkenToast** [comment]
Another thing that I have noticed with this problem is that the touchpad does not cause this behaviour. It only happens if I drag windows around with my mouse.

Touchpad works smoothly and doesn't cause any glitching.

**Comment by Leleat** [comment]
I've created the branch https://github.com/Leleat/Tiling-Assistant/tree/new-movement-test where I now use a timer like WinTile. 

Can you test it and see if it actually fixes the issue?

**If it does**, could you please go to the advanced settings (in the titlebar of the preferences is a button to go the advanced settings) and enable the setting `Hybrid Movement`. I tried to mix the movement and timer based approach to reduce the calls of my functions while keeping the delay because of the timer low. Does the Hyrbid Mode lag for you?

**Comment by gnat** [comment]
@Leleat Excellent work dude! The new version works with zero lag. :laughing: 

> Can you test it and see if it actually fixes the issue?

It does. Well done!

> Does the Hyrbid Mode lag for you?

Seemingly zero lag as well. No noticeable difference.

**Comment by Leleat** [comment]
Thanks for the confirmation.

Do you notice any delay in the updates of the tiling preview compared to the current `main` or the version on EGO on your more powerful system?

**Comment by gnat** [comment]
It seems less laggy on my main machine as well now when I have a lot of other stuff going on.

Can't easily tell the difference between Hybrid and non-Hybrid mode.

It's a solid update, I'd say ship it. :shipit:

**Comment by Leleat** [comment]
FYI, I made the timer-based approach mentioned in this issue opt-in in `main` / the next extension version because someone in https://github.com/Leleat/Tiling-Assistant/issues/190 mentioned that it felt worse. It's called `Low Performance Movement Mode` under the advanced settings.
