### ISSUE TITLE
Extension point conflict: there is already a status indicator for role tiling-mode-button

### ISSUE THREAD

**Issue by digitalec** [Leleat/Tiling-Assistant#80]
**Describe the bug**

Woke laptop from sleep and extension was not enabled. Opened Extensions app and noticed the following error:

`Gio.IOErrorEnum: Error opening file “/home/digitalec/.config/tiling-assistant/tiledSessionRestore.json”: No such file or directory`

I removed the extension, deleted ~/.config/tiling-assistant directory and reinstalled the extension which now shows this error:

`Extension point conflict: there is already a status indicator for role tiling-mode-button`

**Steps To Reproduce**

Install extension, sleep, wake up and error was present.

**Screenshots/-captures**

**System Info:**
 - Distro (incl. version): Fedora 34
 - GNOME version: 40.1.0

 - Extensions version: 21
 - XOrg/Wayland: Wayland

**Journalctl logs**

```
JS ERROR: Extension tiling-assistant@leleat-on-github: Error: Extension point conflict: there is already a status indicator for role tiling-mode-button
addToStatusArea@resource:///org/gnome/shell/ui/panel.js:1060:19
SemiAutoTilingMode@/home/digitalec/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/tilingSemiAutoMode.js:22:34
enable@/home/digitalec/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/extension.js:120:23
_callExtensionEnable@resource:///org/gnome/shell/ui/extensionSystem.js:167:32
loadExtension@resource:///org/gnome/shell/ui/extensionSystem.js:350:26
callback@resource:///org/gnome/shell/ui/extensionDownloader.js:229:39
gotExtensionZipFile/<@resource:///org/gnome/shell/ui/extensionDownloader.js:106:13
```

**Additional context**

Even with the extension showing as disabled in Extensions app and in an error state, I am still able to snap windows to a quarter of the screen but they don't stick to the corner (they stay with the cursor even when mouse button is no longer pressed).

**Comment by Leleat** [comment]
Thanks for the report. I don't know how the extensions system works with sleep (only tried suspend and lock before). I'll look into it.

> Extension point conflict: there is already a status indicator for role tiling-mode-button

I guess this is related to the sleep problem. Restarting GNOME Shell should "fix" it (on Wayland you need to at least logout).

**Comment by Leleat** [comment]
I think I mixed up the terminology here... When you say sleep, you are talking about suspending or hibernating?

**Comment by digitalec** [comment]
Suspend. I had closed the lid for a couple hours and when I signed back in it was acting up.

I tested it again just now. Logging out and back in does fix it after doing suspend (this time suspended only for 10s to test).

**Comment by Leleat** [comment]
I can't reproduce this error exactly. Only way for me to get `Gio.IOErrorEnum: Error opening file “/home/digitalec/.config/tiling-assistant/tiledSessionRestore.json”: No such file or directory` is to not have the `~/.config/tiling-assistant` directory when the screen is locked (which happens when you suspend). But you said

> deleted ~/.config/tiling-assistant

So I assume when the screen got locked, you already had `~/.config/tiling-assistant` directory, right?

**Comment by Leleat** [comment]
I've pushed a commit to fix the crash, if the config dir didn't exist on screenlock. My only remaining question to see, if that was related to this issue:

> when the screen got locked, you already had ~/.config/tiling-assistant directory, right?

**Comment by digitalec** [comment]
I did not have that directory. I assumed it would be recreated upon reinstall of the extension but after removing the directory and uninstalling the extension, reinstalling the extension did not recreate the config directory. I'll test it shortly. Thanks!

**Comment by Leleat** [comment]
The config dir only gets created, if it's needed. That means, if you created a layout or locked the screen. The latter case was bugged (but fixed with the latest commit).

**Comment by digitalec** [comment]
When I received the error regarding tilingSessionRestore.json being missing, the directory existed.

I applied your commit locally to `extension.js` which didn't fix the issue. If the directory exists on sleep, it creates tilingSessionRestore.json with contents `[]`. If the directory does not exist, I still receive the original error:

`Gio.IOErrorEnum: Error opening file “/home/digitalec/.config/tiling-assistant/tiledSessionRestore.json”: No such file or directory`

I can't reproduce the `Extension Point Conflict` error now, with or without the latest commit applied. I'm not sure why but I can reproduce the previous tiledSessionRestore.json error each time (if the directory is missing) - with or without the latest commit.

**Comment by Leleat** [comment]
Ah, glad to hear, I'll update the EGO version then. Thanks for the cooperation!

**Comment by digitalec** [comment]
That makes sense. Thanks for fixing it so quickly!
