### ISSUE TITLE
Support old Gnome on RHEL 8 / CentOS 8

### ISSUE THREAD

**Issue by rungitringit** [Leleat/Tiling-Assistant#93]
Hello,
Thanks so much for this, I'm loving it on Fedora systems!

We'd love to use it at work, but RHEL 8 is still on gnome-shell 3.32.2-30. :(
Is there any chance you'd be able to adapt it back to an old version of Gnome please?

PS: Happy if there are less features

**Comment by Leleat** [comment]
I've only switched to GNOME with 3.34 but I'll take a look. 

> PS: Happy if there are less features

Heh, I did consider making a "small brother" of this extension since I personally am not using quite a few of the features myself (like the layouts etc...). What features are you fine with being removed?

**Comment by rungitringit** [comment]
Thanks so much for considering this!

I expect the team will mainly want snap to corners (and Top or bottom) and the keyboard shortcuts to do the same things.

Any other features would be a bonus!

There's another Gnome extension which has some overlap with yours but it's often too complex for people to learn and doesn't snap to corners.

**Comment by coreybx** [comment]
Agreed, This would be great!

**Comment by Leleat** [comment]
> We'd love to use it at work, but RHEL 8 is still on gnome-shell 3.32.2-30

Sorry, I am not sure how to read the version number here. Is the "-30"  some patch version of RHEL 8 or do you mean that your systems are on either on GNOME 3.30 or 3.32?

**Comment by rungitringit** [comment]
Thank you for trying!
Does that mean that snap to corners can't work?

The version is a patch of Gnome 3.32.

**Comment by Leleat** [comment]
>  Does that mean that snap to corners can't work?

You can still snap to corners but you won't get the "Tiling Popup" (the altTab looking thing, which appears when a window is tiled and there is free screen space. It lists the open windows on the current workspace to fill the rest of the screen. Here is a [screenshot](https://github.com/Leleat/Tiling-Assistant/blob/master/GUIDE.md#Tiling-Popup))

**Comment by rungitringit** [comment]
Ah right. We could actually live without that if you're interested in releasing a "lite" version for older Gnome versions!

Just basic snapping and the keyboard shortcuts would go a long way! (I don't understand why Gnome still hasn't implemented it)


Thanks again!

**Comment by Leleat** [comment]
I've finished the port for GNOME Shell 3.32 & 3.34 at https://github.com/Leleat/Tiling-Assistant/tree/lite-version. I still need to rename it and give it a unique ID before I can publish on EGO (which I'll do next week) but it should be working.

It'd be helpful, if you could test it on the older GNOME versions. I only gave them a quick spin in a VM on 3.32 and 3.34.

FTR, I've removed the `Layouts` and the `PieMenu`. I've disabled/hidden the `Tiling Popup` and the `Tile Editing Mode` for GNOME Shell 3.32 and 3.34... so in the end all of my unique features are gone, and only the quarter tiling and ctrl-drag tiling are left, if you are on GNOME 3.32 or 3.34. That means you might be interested in other extensions, which offer these features.

For example:
https://extensions.gnome.org/extension/657/shelltile/
https://extensions.gnome.org/extension/1723/wintile-windows-10-window-tiling-for-gnome/ (doesn't support a ctrl-drag)

They've started out earlier than me. So their support for older GNOME versions should already be well tested.

**Comment by coreybx** [comment]
Hey thanks for your work. I’ve tried your new fix with RHEL8 and it still presents with issues. It says the required gtk+ version is not the supported 3.24. Current version is 3.22

**Comment by Leleat** [comment]
> Hey thanks for your work. I’ve tried your new fix with RHEL8 and it still presents with issues. It says the required gtk+ version is not the supported 3.24. Current version is 3.22

Ah, I see. I've tested it on Fedora 30/31 (GNOME Shell 3.32/3.34)... guess it comes with a newer GTK version. I think that bug should only apply to opening the settings. Can you still enable the extension and use it (e. g. quarter tiling...)?

Anyway, I'll fix that issues.

**Comment by Leleat** [comment]
@coreybx I can't find any docs for GTK 3.22 (only found 3.24)... Could open `/home/toni/.local/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/prefs.ui` and change the gtk version from `'3.24'` to `'3.22'`. Do you still get any errors?

**Comment by rungitringit** [comment]
Thanks again @Leleat 

We've changed that version and the tiling-assistant configuration UI is now displayed, but the extension does not work and `sudo journalctl /usr/bin/gnome-shell` has an entry:

`Extension "tiling-assistant@leleat-on-github" had error: TypeError: this.tilePrievew.destroy is not a function`

We're having problems finding any more errors associated with this extension.

Note that we've put it in to `/usr/share/gnome-shell/extensions` as we'll be making it enabled by default for all users on our systems.

**Comment by Leleat** [comment]
> Extension "tiling-assistant@leleat-on-github" had error: TypeError: this.tilePreview.destroy is not a function

fixed it with latest commit. Can you please try a clean install of the extension (remove old extension, reload gnome shell and move the extension folder to the correct location and reload GNOME Shell again)?

**Comment by rungitringit** [comment]
Thanks again for that!

It worked for a while for me, I was then idle for a long time and found that it totally stopped working.  How can we troubleshoot or diagnose problems?

@coreybx found that snap to corners was never working for him, but the keyboard shortcuts were.

**Comment by Leleat** [comment]
> It worked for a while for me, I was then idle for a long time and found that it totally stopped working. How can we troubleshoot or diagnose problems?
>
> @coreybx found that snap to corners was never working for him, but the keyboard shortcuts were.

Journalctl is the only place where you can find "faulty code". You could try to add "log"s into the code. They will get printed to journalctl as well. For example `log("print whatever...");`. 

Since the keyboard shortcuts are working: The file `tilingGrabHandler.js` handles the grab (moving and resizing) of a window. The function `onMoving` is called whenever a window is being moved. That function calls `_previewTile`, which should show the blue tile preview, if you are moving a window along the screen edges.

> It worked for a while for me, I was then idle for a long time and found that it totally stopped working

No idea, tbh. Maybe something specific to your system setup. I am not familiar with multi-user extension systems... could you explain how your systems are setup? I'll then try and ask on the GNOME Shell extensions matrix channel, if someone has any ideas.

**Comment by rungitringit** [comment]
Hello,

We're just following the Gnome documentation so that the systems we build will offer this extension to all users by default.

See https://help.gnome.org/admin/system-admin-guide/stable/extensions-enable.html.en

We currently don't plan to add any other custom extensions.

**Comment by rungitringit** [comment]
These messages were displayed much later in the day, but could be related to the problem:

```
gnome-shell[325212]: JS ERROR: TypeError: otherWindow.tileGroup is null
                     dissolveTileGroupFor/<@/usr/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/tilingUtil.js:626:9
                     dissolveTileGroupFor@/usr/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/tilingUtil.js:625:2
                     updateTileGroup/</window.unmanagedDissolvedId<@/usr/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/tilingUtil.js:605:66
org.gnome.Shell.desktop[325212]: # watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
org.gnome.Shell.desktop[325212]: # unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
org.gnome.Shell.desktop[325212]: # watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
```

I found just now that the tiling assistant extension was not enabled in gnome-tweak-tools.  I flipped the switch to "ON" and the window hung for ~10 seconds.   Tiling assistant didn't work afterwards.

I've just tried the tweaks UI again.  Disabled tiling-assistant and then enabled it.  It is currently working again!   So confusing.

We'll try to gather more evidence.

**Comment by Leleat** [comment]
> These messages were displayed much later in the day, but could be related to the problem: [...]

Ah, I see. I know where that problems comes from*. I'll fix it. It might have caused the other issues. 

*I had to use a different signal/event because the one I used before didn't exist pre-3.34. I guess something racey may be going on here and that's why it may work at first. But once you hit the first bug, it causes the shenanigans.

**Comment by Leleat** [comment]
> ```
> gnome-shell[325212]: JS ERROR: TypeError: otherWindow.tileGroup is null
>                      dissolveTileGroupFor/<@/usr/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/tilingUtil.js:626:9
>                      dissolveTileGroupFor@/usr/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/tilingUtil.js:625:2
>                      updateTileGroup/</window.unmanagedDissolvedId<@/usr/share/gnome-shell/extensions/tiling-assistant@leleat-on-github/tilingUtil.js:605:66

I've pushed a new commit, which hopefully fixes this^ error (the terminal messages aren't related to my extension) Can you please test it and see, if you got any other errors?

**Comment by rungitringit** [comment]
@Leleat thanks very much for this!
We will grab that version and test it when we're able.

**Comment by coreybx** [comment]
Thanks for you help with this and the regular commits. I've just tried your latest to this with our Gnome-shell 3.22

`gnome-shell[1234]: JS ERROR: Could not load extension tiling-assistant@leleat-on-github: Error: Failed to load me>
                                                       createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:232:19
                                                       _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:502:29
                                                       collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:25:17
                                                       _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:486:9
                                                       _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:516:13
                                                       _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:547:13
                                                       init@resource:///org/gnome/shell/ui/extensionSystem.js:35:9
                                                       _initializeUI@resource:///org/gnome/shell/ui/main.js:223:5
                                                       start@resource:///org/gnome/shell/ui/main.js:125:5
                                                       @<main>:1:31`

**Comment by coreybx** [comment]
also can you please support gnome 3.22 in the prefs file. as i need to change that each time.

Cheers

**Comment by Leleat** [comment]
> also can you please support gnome 3.22 in the prefs file. as i need to change that each time.

Supporting 3.22 would require some extra work. I thought your systems were on 3.32?

Is it already running on your 3.32 Systems?

**Comment by rungitringit** [comment]
@Leleat I think @coreybx is referring to GTK 3.22 for which you asked us to change a file in:

https://github.com/Leleat/Tiling-Assistant/issues/93#issuecomment-913790699

**Comment by coreybx** [comment]
yes apologies i meant 3.32, CENTOS\RHEL 8 version

**Comment by Leleat** [comment]
> @Leleat I think @coreybx is referring to GTK 3.22 for which you asked us to change a file in:

Ah, my bad. Completely forgot about that. Done it now.

> ```gnome-shell[1234]: JS ERROR: Could not load extension tiling-assistant@leleat-on-github: Error: Failed to load me> createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:232:19 _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:502:29 collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:25:17 _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:486:9 _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:516:13 _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:547:13 init@resource:///org/gnome/shell/ui/extensionSystem.js:35:9 _initializeUI@resource:///org/gnome/shell/ui/main.js:223:5 start@resource:///org/gnome/shell/ui/main.js:125:5 @<main>:1:31```

I'll try to look for a CentOS iso and see if I can run it in a VM for easier debugging.

**Comment by Leleat** [comment]
> ```gnome-shell[1234]: JS ERROR: Could not load extension tiling-assistant@leleat-on-github: Error: Failed to load me> createExtensionObject@resource:///org/gnome/shell/ui/extensionSystem.js:232:19 _loadExtensions/<@resource:///org/gnome/shell/ui/extensionSystem.js:502:29 collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:25:17 _loadExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:486:9 _enableAllExtensions@resource:///org/gnome/shell/ui/extensionSystem.js:516:13 _sessionUpdated@resource:///org/gnome/shell/ui/extensionSystem.js:547:13 init@resource:///org/gnome/shell/ui/extensionSystem.js:35:9 _initializeUI@resource:///org/gnome/shell/ui/main.js:223:5 start@resource:///org/gnome/shell/ui/main.js:125:5 @<main>:1:31```

I installed CentOS 8 in a VM and tried out the latest commit. I cannot reproduce this bug... How did you encounter it? Here is a short gif of me using the extension in a fresh install

![output](https://user-images.githubusercontent.com/53054301/133130672-0745cd80-4aa1-4355-bdf7-af3438706d9a.gif)

Can you disable all other extensions and try a clean reinstall (disable extension, delete tiling assistant's extension folder, restart gnome shell, move the tiling assistant's folder back to `/usr/...` and reload GNOME Shell again)?

**Comment by rungitringit** [comment]
Hello,
We do not have any other extensions installed - only the built-in ones.

We can "re load" it as you describe though.

**Comment by rungitringit** [comment]
Your latest version still has problems for us on RHEL 8 (not CentOS streams 8 - slightly older versions of packages).
The older with the GTK version modification has occasional errors in the journal but otherwise seems to work.

**Comment by Leleat** [comment]
> Your latest version still has problems for us on RHEL 8 (not CentOS streams 8 - slightly older versions of packages).
The older with the GTK version modification has occasional errors in the journal but otherwise seems to work.

Could you describe the the problems/error a bit more?

**Comment by rungitringit** [comment]
We've got a few fires going on, but when they've been put out we'll do so!

**Comment by Leleat** [comment]
Since I can't reproduce the problems (with the same system in a VM), have no clue what the problem could be and I am personally not that invested into supporting old GNOME versions, I am gonna give up on this, sorry.

**Comment by rungitringit** [comment]
@Leleat thank you for your help with this and your willingness to try to reproduce problems.

We're aware that you were waiting on feedback from us.  I'm sorry we've been really busy and I was away on a week's leave.

It's possible that the code we have running today, which is a combination of fixes, could be committed and used as a stable release.  Are you willing to re-open this and keep it open for a few more weeks while we try to sort that out please?

**Comment by Leleat** [comment]
> It's possible that the code we have running today, which is a combination of fixes, could be committed and used as a stable release. Are you willing to re-open this and keep it open for a few more weeks while we try to sort that out please?

Sure.

**Comment by rungitringit** [comment]
PS: Ever thought of registering for BAT?  You'll find a few coins in your wallet :-D

**Comment by Leleat** [comment]
BAT? Basic attention token
?

**Comment by rungitringit** [comment]
> BAT? Basic attention token?
> 
> [Edit] Sorry, accidently closed...
> 
> PS. Not really interested in crypto, but thanks :)

Yes, I'm not interested in crypto energy wasting speculation either, but I do like Brave's model.

**Comment by coreybx** [comment]
> gonna give up on th

All good, it is now working. Not sure what the issue was when i tried it but I've now finally since redeployed the latest lite version and it's all working. 

Sorry i haven't had time to get round to doing it and i appreciate your hard work going to the efforts of deploying the lite version. 

Cheers!
